config/routes.rb
Rails.application.routes.draw do

  root 'high_voltage/pages#show', :id => 'index'
  resources :posts do
    resources :comments
  end

  resources :milestones
  resources :tags
  resources :portfolios
  resources :coders

  resources :coder_sessions, only: [:new, :create, :destroy]

  get 'login' => 'coder_sessions#new'
  get 'logout' => 'coder_sessions#destroy'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts, through: :taggings

  def to_s
    name
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

before_action :require_login, only: [:destroy]

  def show
    @tag = Tag.find(params[:id])
  end

  def index
    @tags = Tag.all
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    flash.notice = "Tag '#{@tag.name}' destroyed!"
    redirect_to tags_path
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/index.html.erb
<div class="container">
  <h1>Post Tags</h1>

<ul >
  <% @tags.each do |tag| %>
    <li class="boxed">
        <%= link_to tag.name, tag_path(tag) %>
    </li><br>
  <% end %>
</ul>

<div class="row"
<div class="col-md-3"><%= link_to "List All Posts", posts_path %></div>
</div>
</div> <!--container-->

app/views/tags/show.html.erb
<div class = "container">
<h1>Posts Tagged With Tag: <%= @tag.name %> </h1>

<ul>
  <% @tag.posts.each do |post| %>
    <li class="boxed"> <%= link_to post.title, post_path(post) %> </li><br>
    <% end %>
</ul>

<div class="row">
<div class="col-md-3"><%= link_to "Delete Tag", tag_path(@tag), method: :delete, data: {confirm: "Do you really want to delete this tag?"} %></div>
  <div class="col-md-3"><%= link_to "List All Posts", posts_path %></div>
</div> <!--row-->

</div>