config/routes.rb
Rails.application.routes.draw do

  root 'high_voltage/pages#show', :id => 'index'
  resources :posts do
    resources :comments
  end

  resources :milestones
  resources :tags
  resources :portfolios
  resources :coders

  resources :coder_sessions, only: [:new, :create, :destroy]

  get 'login' => 'coder_sessions#new'
  get 'logout' => 'coder_sessions#destroy'

end

app/models/post.rb
class Post < ActiveRecord::Base
   include ActionView::Helpers::TextHelper

  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings

  def get_body
    simple_format(self.body)
  end

  def tag_list
    tags.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :require_login, except: [:index, :show]

  def index
    @posts = Post.all.order(date_written: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comment.post_id = @post.id
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    flash.notice = "Post '#{@post.title}' created!"
    redirect_to post_path(@post)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    flash.notice = "Post '#{@post.title}' updated!"
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash.notice = "Post '#{@post.title}' deleted!"
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :tag_list, :date_written, :author)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comment.html.erb
<div class="boxed">
  <h4>Comment by: <%= comment.author_name %> </h4>
  <p>Posted <%= distance_of_time_in_words(comment.post.created_at, comment.created_at) %> later </p>
</div>

<div class="boxed"><%= comment.body %>

</div>

<br><br>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <ul>
  <% @post.errors.full_messages.each do |error| %>
    <li><%= error %></li>
    <% end %>
  </ul>

  <p>
    <%= f.label :title %><br/>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :author %><br/>
    <%= f.text_field :author %>
  </p>

  <p>
    <%= f.label :date_written %><br/>
    <%= f.date_select :date_written %><br/>
  </p>

  <p>
    <%= f.label :body, "Content" %><br/>
    <%= f.text_area :body, :size => "50x50" %>
  </p>

  <p>
    <%= f.label :tag_list %><br/>
    <%= f.text_field :tag_list %>
  </p>

  <p>
    <%= f.submit %>
  </p>

  <% end %>

app/views/posts/edit.html.erb
<div class= "container">

<h1>Edit Post</h1>

<%= render partial: 'form' %>

</div>

app/views/posts/index.html.erb
<div class="container">

<div>
  <h1 class="boxed"> Three-Month Coder Blog</h1>
</div>

<br/><br/>

<div class="row">

        <div class="col-sm-8 blog-main">
          <% if logged_in? %>
              <p> <%= link_to "Write A New Post", new_post_path %>
              </p>
          <% end %>

        <% @posts.each do |post| %>
          <div class="blog-post">
            <h2 class="blog-post-title"><strong><%= link_to post.title, post%></strong></h2>

            <p><% if logged_in? %>
                <%= link_to 'Edit', edit_post_path(post) %> |
                <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
            </p>
            <% unless post.date_written.nil? %>
            <p class="blog-post-meta"><span class="glyphicon glyphicon-calendar"> </span><%= post.date_written.strftime('%B %-d, %Y') %> | <span class="glyphicon glyphicon-pencil"> </span><%= post.author %> | <span class="glyphicon glyphicon-tags"></span> &nbsp;Related Articles:
            <% post.tags.each do |tag| %>
              <%= link_to tag.name, tag_path(tag) %>
              <% end %>
            </p>
            <% end %>
            <p><%= truncate(post.body, length: 500, separator: ' ')%> <%=link_to 'Continue reading ...', post_path(post)%>
            </p>
          </div> <!-- blog post -->
          <% end %>
      </div> <!-- col-sm-8 blog-main -->

      <!-- start sidebar section -->
      <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
          <div class="sidebar-module sidebar-module-inset">
            <h4><strong>About These Posts</strong></h4>
            <p>These posts represent thoughts, techniques, and analysis of Ruby, Rails, programming, and life in general.</p>
          </div>
          <div class="sidebar-module">
            <h4><strong>List of All Posts</strong></h4>
            <ul class="list">
              <% @posts.each do |post| %>
                <li><%= link_to post.title, post_path(post) %></li>
              <% end %>
            </ul>
          </div>
        </div><!-- end col-sm-3 and sidebar section-->

</div> <!-- row -->

<% if logged_in? %>
<p> <%= link_to "Write A New Post", new_post_path %>
</p>
<% end %>

</div> <!-- end container -->

app/views/posts/new.html.erb
<div class="container">

<h1> Create A New Post </h1>

<%= render partial: 'form' %>

</div>

app/views/posts/show.html.erb
<div class="container">

<div class="boxed">
<h1 style = "text-align: center"> <%= @post.title %> </h1>

<p><span class="glyphicon glyphicon-calendar"> </span><%= @post.date_written.strftime('%B %-d, %Y') %> | <span class="glyphicon glyphicon-pencil"> </span><%= @post.author %> | <span class="glyphicon glyphicon-tags"></span> &nbsp;Related Articles:
  <% @post.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
    <% end %>
</p>
</div>

<br/>

<!--used simple_format text helper to format output -->
<div id = "postbody" class="boxed">
<p> <%= @post.get_body %> </p>
</div>

<p>

<div class="row">
  <div class="col-md-3"><%= link_to "List All Posts", posts_path %></div>
  <div class="col-md-3"><%= link_to "List All Post Categories", tags_path %></div>
  <% if logged_in? %>
  <div class="col-md-3"><%= link_to "Edit Post", edit_post_path(@post) %></div>
  <div class="col-md-3"><%= link_to "Delete Post", post_path(@post), method: :delete, data: {confirm: "Do you really want to delete this post?"} %></div>
  <% end %>
</div>
<br><br>
<div class="row">

  <!--Disqus Comments -->
<%= render partial: "disqus/thread", locals: {post: @post} %>

</div>