config/routes.rb
Rails.application.routes.draw do

  root 'high_voltage/pages#show', :id => 'index'
  resources :posts do
    resources :comments
  end

  resources :milestones
  resources :tags
  resources :portfolios
  resources :coders

  resources :coder_sessions, only: [:new, :create, :destroy]

  get 'login' => 'coder_sessions#new'
  get 'logout' => 'coder_sessions#destroy'

end

app/models/coder.rb
class Coder < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/milestone.rb
class Milestone < ActiveRecord::Base
end

app/models/portfolio.rb
class Portfolio < ActiveRecord::Base
  has_attached_file :image1, styles: {medium: "1000x1000>", thumb: "100x100>"}
  validates_attachment_content_type :image1, :content_type => /\Aimage\/.*\Z/
  validates_attachment_file_name :image1, :matches => [/png\Z/, /jpe?g\Z/]

end

app/models/post.rb
class Post < ActiveRecord::Base
   include ActionView::Helpers::TextHelper

  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings

  def get_body
    simple_format(self.body)
  end

  def tag_list
    tags.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
    self.tags = new_or_found_tags
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :taggings
  has_many :posts, through: :taggings

  def to_s
    name
  end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :post
end

app/controllers/coders_controller.rb
class CodersController < ApplicationController
  before_action :set_coder, only: [:show, :edit, :update, :destroy]

  before_action :zero_coders_or_authenticated, only: [:new, :create]

  before_action :require_login, except: [:new, :create]

  # GET /coders
  # GET /coders.json
  def index
    @coders = Coder.all
  end

  # GET /coders/1
  # GET /coders/1.json
  def show
  end

  # GET /coders/new
  def new
    @coder = Coder.new
  end

  # GET /coders/1/edit
  def edit
  end

  # POST /coders
  # POST /coders.json
  def create
    @coder = Coder.new(coder_params)

    respond_to do |format|
      if @coder.save
        format.html { redirect_to @coder, notice: 'Coder was successfully created.' }
        format.json { render :show, status: :created, location: @coder }
      else
        format.html { render :new }
        format.json { render json: @coder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coders/1
  # PATCH/PUT /coders/1.json
  def update
    respond_to do |format|
      if @coder.update(coder_params)
        format.html { redirect_to @coder, notice: 'Coder was successfully updated.' }
        format.json { render :show, status: :ok, location: @coder }
      else
        format.html { render :edit }
        format.json { render json: @coder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coders/1
  # DELETE /coders/1.json
  def destroy
    @coder.destroy
    respond_to do |format|
      format.html { redirect_to coders_url, notice: 'Coder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coder
      @coder = Coder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coder_params
      params.require(:coder).permit(:username, :email, :password, :password_confirmation)
    end

    def zero_coders_or_authenticated
      unless Coder.count == 0 || current_user
        redirect_to root_path
        return false
      end
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_action :require_login, except: [:create]

  def create
    @comment = Comment.new(comment_params)
    @comment.post_id = params[:post_id]
    @comment.save
    redirect_to post_path(@comment.post)
  end

  private

  def comment_params
    params.require(:comment).permit(:author_name, :body)
  end

end

app/controllers/milestones_controller.rb
class MilestonesController < ApplicationController
before_action :require_login, except: [:index]

  def index
    @milestones = Milestone.all.order(date_worked: :desc)
    @total_hours = Milestone.all.map do |milestone| milestone.hours
    end.inject(:+)
  end

  def new
    @milestone = Milestone.new
  end

  def create
    @milestone = Milestone.new(milestone_params)
    @milestone.save
    flash.notice = "Milestone #{@milestone.date_worked} created!"
    redirect_to milestones_path
  end

  def edit
    @milestone = Milestone.find(params[:id])
  end

  def update
    @milestone = Milestone.find(params[:id])
    @milestone.update(milestone_params)
    flash.notice = "Milestone '#{@milestone.date_worked}' updated!"
    redirect_to milestones_path
  end

  def destroy
    @milestone = Milestone.find(params[:id])
    @milestone.destroy
    flash.notice = "Milestone '#{@milestone.date_worked}' deleted!"
    redirect_to milestones_path
  end

  private

  def milestone_params
    params.require(:milestone).permit(:date_worked, :time, :hours, :activity)
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
before_action :require_login, except: [:index, :show]

  def index
    @posts = Post.all.order(date_written: :desc)
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comment.post_id = @post.id
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    flash.notice = "Post '#{@post.title}' created!"
    redirect_to post_path(@post)
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(post_params)
    flash.notice = "Post '#{@post.title}' updated!"
    redirect_to post_path(@post)
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash.notice = "Post '#{@post.title}' deleted!"
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, :tag_list, :date_written, :author)
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

before_action :require_login, only: [:destroy]

  def show
    @tag = Tag.find(params[:id])
  end

  def index
    @tags = Tag.all
  end

  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    flash.notice = "Tag '#{@tag.name}' destroyed!"
    redirect_to tags_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coder_sessions_helper.rb
module CoderSessionsHelper
end

app/helpers/coders_helper.rb
module CodersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/milestones_helper.rb
module MilestonesHelper
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/disqus/_thread.html.erb
<div id="disqus_thread"></div>
<script type="text/javascript">

  var disqus_shortname = "threemonthcoder";
    var disqus_identifier = "<%= post.id -%>";
    var disqus_url = '<%= request.original_url -%>';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function() {
        var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
        dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
        (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>

app/views/layouts/_footer.html.erb
<div id="copyright">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3 centered">
          <h5>A Ruby-on-Rails site<br/></h5>
          <br/>
          <h5>Preston Copeland | 2015</h5><br>
        </div>
      </div>
      <div class="row">
        <%= mail_to("copelandps1@gmail.com", "Email Me") %>
      </div>
    </div>
  </div>

app/views/layouts/_navigation.html.erb
<section id="navbar-main">
      <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <%= link_to "Three-Month Coder", page_path('index'), class: "navbar-brand" %>
          </div>
          <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
              <li class="active"><%= link_to "HOME", page_path('index'), class: "smoothScroll" %></li>
              <li><%= link_to "PROGRESS LOG", milestones_path, class: "smoothScroll" %> </li>
              <li><%= link_to("BLOG POSTS", posts_path, class: "smoothScroll") %></li>
              <li><%= link_to "PORTFOLIO", portfolios_path, class: "smoothScroll" %></li>
              <li><%= link_to "ABOUT", page_path('about'), class: "smoothScroll" %> </li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
  </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ThreeMonthCoder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
      <%= render 'layouts/navigation' %>
  </header>
  <br><br><br>
  <main role = "main">

    <div class = "container"><p><%= flash.notice %></p></div>

    <%= yield %>
  </main>

  <div class="container">
  <h5>
  <% if logged_in? %>
    <%= "Logged in as #{current_user.email}" %>
    <%= link_to "Logout", logout_path %>
  <% else %>
    <%= link_to "Login", login_path %>
  <% end %>
  </h5>
  </div>

  <footer>
  <%= render 'layouts/footer' %>
  </footer>

<!-- Disqus JavaScript -->
<script type="text/javascript">
    /* * * CONFIGURATION VARIABLES * * */
    var disqus_shortname = 'threemonthcoder';

    /* * * DON'T EDIT BELOW THIS LINE * * */
    (function () {
        var s = document.createElement('script'); s.async = true;
        s.type = 'text/javascript';
        s.src = '//' + disqus_shortname + '.disqus.com/count.js';
        (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
    }());
</script>
</body>
</html>

app/views/pages/about.html.erb
<div class="container">

<div>
<h1 class="boxed"> About This Coder </h1>

</div>
<br/><br/>

<div class="boxed">
<p>Hello. My name is Preston Copeland.</p>

<p>I have three months to seriously level up. I want to systematically increase my prowess. I started on April 21, 2015. The race is on. The end date is July 21, 2015. My goal is to log at least 300 hours of genuine work. (Updated goal, June 6): My goal is to log at least 500 hours of genuine work.
</p>

<p>My plan is to work through tutorials, coding exercises, books, and projects in order to level up as a developer.</p>

</div>
</div>

app/views/pages/index.html.erb
<!-- ********** SLIDES ********** -->
      <section id="slides">
         <ul class="slides-container">
            <li>
               <%= image_tag("slide-a.jpg") %>
            </li>
            <li>
               <%= image_tag("slide-b.jpg") %>
            </li>
            <li>
               <%= image_tag("slide-c.jpg") %>
            </li>
         </ul>

         <div id="bannertext">
            <h1>THREE-MONTH CODER</h1>
            <hr class="aligncenter">
            <h3>One man's quest to level up as a coder.<br> In three months.</h3>

            <p>
              <%= link_to("Progress Log", milestones_path, class: "btn btn-lg btn-white btn-design") %>

              <%= link_to("Portfolio", portfolios_path, class: "btn btn-lg btn-white btn-design") %>
            </p>
         </div>
         <!-- end:Banner text -->

         <nav class="slides-navigation">

            <%= link_to page_path("index"), class: "prev" do %>
              <i class="glyphicon glyphicon-chevron-left"></i>
              <% end %>
            <%= link_to page_path("index"), class: "next" do %>
              <i class="glyphicon glyphicon-chevron-right"></i>
              <% end %>

         </nav>

      </section>
      <!-- END SLIDES SECTION -->


<!-- ********** FEATURES ********** -->
  <div class="container">
    <div class="row mtb2 centered">

      <div class="col-md-4 w">
        <div class="circle-icon">
          <div class="icon ion-ios7-gear-outline"></div>
        </div>
        <%= link_to("Progress Log", milestones_path, :class => "index_links") %>
        <hr class="aligncenter">
        <p>Here is where I chart, in excruciating detail, what I've been learning and for how long I've been learning it.</p>
      </div><!--/col-md-4-->

      <div class="col-md-4 w">
        <div class="circle-icon" >
         <div class="icon ion-ios7-analytics-outline"></div>
        </div>
        <%= link_to("Blog Posts", posts_path, :class => "index_links") %>
        <hr class="aligncenter">
        <p>What I'm learning about Ruby, Rails, and programming in general.</p>
      </div><!--/col-md-4-->



      <div class="col-md-4 w">
        <div class="circle-icon">
          <div class="icon ion-ios7-camera-outline"></div>
        </div>
        <%= link_to("Portfolio", portfolios_path, :class => "index_links") %>
        <hr class="aligncenter">
        <p>Screenshots and links to my projects.</p>
      </div><!--/col-md-4-->
    </div><!--/row -->
  </div><!-- /.container -->

<script>
    //Superslides
    $('#slides').superslides({
        slide_easing: 'easeInOutCubic',
        slide_speed: 800,
        pagination: true,
        hashchange: false,
        scrollable: true,
        animation: 'fade'
    });

    // Add swipe option

    $('#slides').hammer().on('swipeleft', function () {
        $(this).superslides('animate', 'next');
    });

    $('#slides').hammer().on('swiperight', function () {
        $(this).superslides('animate', 'prev');
    });
    </script>

    <script>
    // Banner text add parallax efect and fade
  function EasyPeasyParallax() {
      scrollPos = $(this).scrollTop();
      $('#slider').css({
          'background-position': '50% ' + (-scrollPos / 4) + "px"
      });
      $('#bannertext').css({
          'margin-top': (scrollPos / 4) + "px",
          'opacity': 1 - (scrollPos / 250)
      });
  }
  $(document).ready(function () {
      $(window).scroll(function () {
          EasyPeasyParallax();
      });
  });

    </script>