config/routes.rb
Rails.application.routes.draw do

  root 'high_voltage/pages#show', :id => 'index'
  resources :posts do
    resources :comments
  end

  resources :milestones
  resources :tags
  resources :portfolios
  resources :coders

  resources :coder_sessions, only: [:new, :create, :destroy]

  get 'login' => 'coder_sessions#new'
  get 'logout' => 'coder_sessions#destroy'

end

app/models/coder.rb
class Coder < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
end

app/controllers/coders_controller.rb
class CodersController < ApplicationController
  before_action :set_coder, only: [:show, :edit, :update, :destroy]

  before_action :zero_coders_or_authenticated, only: [:new, :create]

  before_action :require_login, except: [:new, :create]

  # GET /coders
  # GET /coders.json
  def index
    @coders = Coder.all
  end

  # GET /coders/1
  # GET /coders/1.json
  def show
  end

  # GET /coders/new
  def new
    @coder = Coder.new
  end

  # GET /coders/1/edit
  def edit
  end

  # POST /coders
  # POST /coders.json
  def create
    @coder = Coder.new(coder_params)

    respond_to do |format|
      if @coder.save
        format.html { redirect_to @coder, notice: 'Coder was successfully created.' }
        format.json { render :show, status: :created, location: @coder }
      else
        format.html { render :new }
        format.json { render json: @coder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coders/1
  # PATCH/PUT /coders/1.json
  def update
    respond_to do |format|
      if @coder.update(coder_params)
        format.html { redirect_to @coder, notice: 'Coder was successfully updated.' }
        format.json { render :show, status: :ok, location: @coder }
      else
        format.html { render :edit }
        format.json { render json: @coder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coders/1
  # DELETE /coders/1.json
  def destroy
    @coder.destroy
    respond_to do |format|
      format.html { redirect_to coders_url, notice: 'Coder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coder
      @coder = Coder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coder_params
      params.require(:coder).permit(:username, :email, :password, :password_confirmation)
    end

    def zero_coders_or_authenticated
      unless Coder.count == 0 || current_user
        redirect_to root_path
        return false
      end
    end
end

app/helpers/coders_helper.rb
module CodersHelper
end

app/views/coders/_form.html.erb
<%= form_for(@coder) do |f| %>
  <% if @coder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coder.errors.count, "error") %> prohibited this coder from being saved:</h2>

      <ul>
      <% @coder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coders/edit.html.erb
<h1>Editing Coder</h1>

<%= render 'form' %>

<%= link_to 'Show', @coder %> |
<%= link_to 'Back', coders_path %>

app/views/coders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Coders</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coders.each do |coder| %>
      <tr>
        <td><%= coder.username %></td>
        <td><%= coder.email %></td>
        <td><%= link_to 'Show', coder %></td>
        <td><%= link_to 'Edit', edit_coder_path(coder) %></td>
        <td><%= link_to 'Destroy', coder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coder', new_coder_path %>

app/views/coders/new.html.erb
<h1>New Coder</h1>

<%= render 'form' %>

<%= link_to 'Back', coders_path %>

app/views/coders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @coder.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @coder.email %>
</p>


<%= link_to 'Edit', edit_coder_path(@coder) %> |
<%= link_to 'Back', coders_path %>